// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDazycs671_h5z4LBB3l6_I0rmAEHUC7mg',
    appId: '1:631207034652:web:51d44aae5261a3352384d9',
    messagingSenderId: '631207034652',
    projectId: 'nothing-ever-happens-dev',
    authDomain: 'nothing-ever-happens-dev.firebaseapp.com',
    storageBucket: 'nothing-ever-happens-dev.firebasestorage.app',
    measurementId: 'G-1GG7V9YJXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5CxNBwjTFuEuOanfOdIyoIHWIOSLnNaY',
    appId: '1:631207034652:android:2cbd5974865538b82384d9',
    messagingSenderId: '631207034652',
    projectId: 'nothing-ever-happens-dev',
    storageBucket: 'nothing-ever-happens-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4M5bmQyOh4MGKsJPy7EfXpN8oml1a8wQ',
    appId: '1:631207034652:ios:69d11a7dc2e065be2384d9',
    messagingSenderId: '631207034652',
    projectId: 'nothing-ever-happens-dev',
    storageBucket: 'nothing-ever-happens-dev.firebasestorage.app',
    iosClientId:
        '631207034652-9h6g86qqrftu7ti16vn3j197qr36pmk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nothingEverHappens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4M5bmQyOh4MGKsJPy7EfXpN8oml1a8wQ',
    appId: '1:631207034652:ios:69d11a7dc2e065be2384d9',
    messagingSenderId: '631207034652',
    projectId: 'nothing-ever-happens-dev',
    storageBucket: 'nothing-ever-happens-dev.firebasestorage.app',
    iosClientId:
        '631207034652-9h6g86qqrftu7ti16vn3j197qr36pmk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nothingEverHappens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDazycs671_h5z4LBB3l6_I0rmAEHUC7mg',
    appId: '1:631207034652:web:8d31633280515a672384d9',
    messagingSenderId: '631207034652',
    projectId: 'nothing-ever-happens-dev',
    authDomain: 'nothing-ever-happens-dev.firebaseapp.com',
    storageBucket: 'nothing-ever-happens-dev.firebasestorage.app',
    measurementId: 'G-LYCK4FFWF7',
  );
}
