// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPUySln1rPeM1bSIIL9tRYeGzNT_mr10I',
    appId: '1:936469690744:web:bb27a0b6f2c88dd3f8708d',
    messagingSenderId: '936469690744',
    projectId: 'nothing-ever-happens-prod',
    authDomain: 'nothing-ever-happens-prod.firebaseapp.com',
    storageBucket: 'nothing-ever-happens-prod.firebasestorage.app',
    measurementId: 'G-G0JD64ZTQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFLZZibTK72dF5wuCKPRarPQSF4SwZsUo',
    appId: '1:936469690744:android:ecb6064b221029d4f8708d',
    messagingSenderId: '936469690744',
    projectId: 'nothing-ever-happens-prod',
    storageBucket: 'nothing-ever-happens-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjy4sMVK5faczddmCeO3QSHxdpxrHkEHc',
    appId: '1:936469690744:ios:911f73cc9e02f796f8708d',
    messagingSenderId: '936469690744',
    projectId: 'nothing-ever-happens-prod',
    storageBucket: 'nothing-ever-happens-prod.firebasestorage.app',
    iosBundleId: 'com.example.nothingEverHappens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjy4sMVK5faczddmCeO3QSHxdpxrHkEHc',
    appId: '1:936469690744:ios:911f73cc9e02f796f8708d',
    messagingSenderId: '936469690744',
    projectId: 'nothing-ever-happens-prod',
    storageBucket: 'nothing-ever-happens-prod.firebasestorage.app',
    iosBundleId: 'com.example.nothingEverHappens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPUySln1rPeM1bSIIL9tRYeGzNT_mr10I',
    appId: '1:936469690744:web:782d560d8aa01e99f8708d',
    messagingSenderId: '936469690744',
    projectId: 'nothing-ever-happens-prod',
    authDomain: 'nothing-ever-happens-prod.firebaseapp.com',
    storageBucket: 'nothing-ever-happens-prod.firebasestorage.app',
    measurementId: 'G-LBNGS96GWK',
  );

}