// Mocks generated by Mockito 5.4.6 from annotations
// in nothing_ever_happens/test/widgets/task_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:nothing_ever_happens/logic/civil_day.dart' as _i7;
import 'package:nothing_ever_happens/logic/task_instance.dart' as _i6;
import 'package:nothing_ever_happens/logic/task_repository.dart' as _i2;
import 'package:nothing_ever_happens/logic/task_schedule.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i2.TaskRepository {
  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
            returnValueForMissingStub: _i3.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  _i4.Future<void> resetLocalDataAndResync() =>
      (super.noSuchMethod(
            Invocation.method(#resetLocalDataAndResync, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Stream<List<_i5.TaskSchedule>> getPersonalTasksForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonalTasksForUser, [userId]),
            returnValue: _i4.Stream<List<_i5.TaskSchedule>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i5.TaskSchedule>>.empty(),
          )
          as _i4.Stream<List<_i5.TaskSchedule>>);

  @override
  _i4.Stream<List<_i6.TaskInstance>> getPersonalInstancesForUser(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonalInstancesForUser, [userId]),
            returnValue: _i4.Stream<List<_i6.TaskInstance>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i6.TaskInstance>>.empty(),
          )
          as _i4.Stream<List<_i6.TaskInstance>>);

  @override
  (_i7.CivilDay, _i5.TaskScheduleRule, int)?
  nextOccurrenceRuleOfScheduleOnOrAfter(
    _i5.TaskSchedule? task,
    _i7.CivilDay? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#nextOccurrenceRuleOfScheduleOnOrAfter, [
              task,
              ref,
            ]),
            returnValueForMissingStub: null,
          )
          as (_i7.CivilDay, _i5.TaskScheduleRule, int)?);

  @override
  _i4.Stream<List<_i5.TaskSchedule>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i4.Stream<List<_i5.TaskSchedule>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i5.TaskSchedule>>.empty(),
          )
          as _i4.Stream<List<_i5.TaskSchedule>>);

  @override
  _i4.Stream<List<_i6.TaskInstance>> getInstances() =>
      (super.noSuchMethod(
            Invocation.method(#getInstances, []),
            returnValue: _i4.Stream<List<_i6.TaskInstance>>.empty(),
            returnValueForMissingStub:
                _i4.Stream<List<_i6.TaskInstance>>.empty(),
          )
          as _i4.Stream<List<_i6.TaskInstance>>);

  @override
  _i4.Future<void> triggerMissedPolicyProcessing() =>
      (super.noSuchMethod(
            Invocation.method(#triggerMissedPolicyProcessing, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addTaskSchedule(_i5.TaskSchedule? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskSchedule, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateTaskSchedule(
    ({Map<String, dynamic> changes, _i5.TaskSchedule newTask})? modification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskSchedule, [modification]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<
    ({List<_i6.TaskInstance> pendingInstances, _i5.TaskSchedule task})?
  >
  deleteTaskSchedule(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTaskSchedule, [id]),
            returnValue:
                _i4.Future<
                  ({
                    List<_i6.TaskInstance> pendingInstances,
                    _i5.TaskSchedule task,
                  })?
                >.value(),
            returnValueForMissingStub:
                _i4.Future<
                  ({
                    List<_i6.TaskInstance> pendingInstances,
                    _i5.TaskSchedule task,
                  })?
                >.value(),
          )
          as _i4.Future<
            ({List<_i6.TaskInstance> pendingInstances, _i5.TaskSchedule task})?
          >);

  @override
  _i4.Future<void> restoreTaskSchedule(
    _i5.TaskSchedule? task,
    List<_i6.TaskInstance>? pendingInstances,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restoreTaskSchedule, [task, pendingInstances]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.TaskInstance?> completeTaskInstance(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeTaskInstance, [id]),
            returnValue: _i4.Future<_i6.TaskInstance?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.TaskInstance?>.value(),
          )
          as _i4.Future<_i6.TaskInstance?>);

  @override
  _i4.Future<void> saveTaskInstance(_i6.TaskInstance? instance) =>
      (super.noSuchMethod(
            Invocation.method(#saveTaskInstance, [instance]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i6.TaskInstance?> dismissTaskInstance(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#dismissTaskInstance, [id]),
            returnValue: _i4.Future<_i6.TaskInstance?>.value(),
            returnValueForMissingStub: _i4.Future<_i6.TaskInstance?>.value(),
          )
          as _i4.Future<_i6.TaskInstance?>);

  @override
  _i4.Future<void> undoResolveTaskInstance(
    _i6.TaskInstance? resolvedInstance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#undoResolveTaskInstance, [resolvedInstance]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
