// Mocks generated by Mockito 5.4.6 from annotations
// in nothing_ever_happens/test/screens/create_task_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:nothing_ever_happens/logic/task_delta.dart' as _i6;
import 'package:nothing_ever_happens/logic/task_repository.dart' as _i2;
import 'package:nothing_ever_happens/logic/task_schedule.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i2.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  _i4.Stream<List<_i5.TaskSchedule>> getPersonalTasksForUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getPersonalTasksForUser, [userId]),
            returnValue: _i4.Stream<List<_i5.TaskSchedule>>.empty(),
          )
          as _i4.Stream<List<_i5.TaskSchedule>>);

  @override
  _i4.Stream<List<_i5.TaskSchedule>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i4.Stream<List<_i5.TaskSchedule>>.empty(),
          )
          as _i4.Stream<List<_i5.TaskSchedule>>);

  @override
  _i4.Stream<List<_i6.TaskDelta>> getHistory() =>
      (super.noSuchMethod(
            Invocation.method(#getHistory, []),
            returnValue: _i4.Stream<List<_i6.TaskDelta>>.empty(),
          )
          as _i4.Stream<List<_i6.TaskDelta>>);

  @override
  _i4.Future<void> addTask(_i5.TaskSchedule? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateTask(
    ({_i6.TaskDelta delta, _i5.TaskSchedule newTask})? modification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [modification]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> completeTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeTask, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
