// Mocks generated by Mockito 5.4.6 from annotations
// in nothing_ever_happens/test/screens/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:nothing_ever_happens/logic/auth_repository.dart' as _i2;
import 'package:nothing_ever_happens/logic/task_instance.dart' as _i8;
import 'package:nothing_ever_happens/logic/task_repository.dart' as _i5;
import 'package:nothing_ever_happens/logic/task_schedule.dart' as _i7;
import 'package:nothing_ever_happens/logic/user_settings.dart' as _i10;
import 'package:nothing_ever_happens/logic/user_settings_repository.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  @override
  _i3.Stream<_i4.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i3.Stream<_i4.User?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.User?>.empty(),
          )
          as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<_i4.User?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i4.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<_i4.User?> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i3.Future<_i4.User?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i5.TaskRepository {
  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  _i3.Stream<List<_i7.TaskSchedule>> getTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, []),
            returnValue: _i3.Stream<List<_i7.TaskSchedule>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i7.TaskSchedule>>.empty(),
          )
          as _i3.Stream<List<_i7.TaskSchedule>>);

  @override
  _i3.Stream<List<_i8.TaskInstance>> getInstances() =>
      (super.noSuchMethod(
            Invocation.method(#getInstances, []),
            returnValue: _i3.Stream<List<_i8.TaskInstance>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i8.TaskInstance>>.empty(),
          )
          as _i3.Stream<List<_i8.TaskInstance>>);

  @override
  _i3.Future<void> addTaskSchedule(_i7.TaskSchedule? task) =>
      (super.noSuchMethod(
            Invocation.method(#addTaskSchedule, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateTaskSchedule(
    ({Map<String, dynamic> changes, _i7.TaskSchedule newTask})? modification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskSchedule, [modification]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<
    ({List<_i8.TaskInstance> pendingInstances, _i7.TaskSchedule task})?
  >
  deleteTaskSchedule(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTaskSchedule, [id]),
            returnValue:
                _i3.Future<
                  ({
                    List<_i8.TaskInstance> pendingInstances,
                    _i7.TaskSchedule task,
                  })?
                >.value(),
            returnValueForMissingStub:
                _i3.Future<
                  ({
                    List<_i8.TaskInstance> pendingInstances,
                    _i7.TaskSchedule task,
                  })?
                >.value(),
          )
          as _i3.Future<
            ({List<_i8.TaskInstance> pendingInstances, _i7.TaskSchedule task})?
          >);

  @override
  _i3.Future<void> restoreTaskSchedule(
    _i7.TaskSchedule? task,
    List<_i8.TaskInstance>? pendingInstances,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restoreTaskSchedule, [task, pendingInstances]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i8.TaskInstance?> completeTaskInstance(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#completeTaskInstance, [id]),
            returnValue: _i3.Future<_i8.TaskInstance?>.value(),
            returnValueForMissingStub: _i3.Future<_i8.TaskInstance?>.value(),
          )
          as _i3.Future<_i8.TaskInstance?>);

  @override
  _i3.Future<_i8.TaskInstance?> uncompleteTaskInstance(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#uncompleteTaskInstance, [id]),
            returnValue: _i3.Future<_i8.TaskInstance?>.value(),
            returnValueForMissingStub: _i3.Future<_i8.TaskInstance?>.value(),
          )
          as _i3.Future<_i8.TaskInstance?>);

  @override
  _i3.Future<_i8.TaskInstance?> dismissTaskInstance(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#dismissTaskInstance, [id]),
            returnValue: _i3.Future<_i8.TaskInstance?>.value(),
            returnValueForMissingStub: _i3.Future<_i8.TaskInstance?>.value(),
          )
          as _i3.Future<_i8.TaskInstance?>);

  @override
  _i3.Future<void> saveTaskInstance(_i8.TaskInstance? instance) =>
      (super.noSuchMethod(
            Invocation.method(#saveTaskInstance, [instance]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> undoResolveTaskInstance(
    _i8.TaskInstance? resolvedInstance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#undoResolveTaskInstance, [resolvedInstance]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> triggerMissedPolicyProcessing({
    _i3.Future<void> Function()? postProcess,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#triggerMissedPolicyProcessing, [], {
              #postProcess: postProcess,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resetLocalDataAndResync() =>
      (super.noSuchMethod(
            Invocation.method(#resetLocalDataAndResync, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getFamilyId() =>
      (super.noSuchMethod(
            Invocation.method(#getFamilyId, []),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserSettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingsRepository extends _i1.Mock
    implements _i9.UserSettingsRepository {
  @override
  _i3.Stream<_i10.UserSettings> getSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, []),
            returnValue: _i3.Stream<_i10.UserSettings>.empty(),
            returnValueForMissingStub: _i3.Stream<_i10.UserSettings>.empty(),
          )
          as _i3.Stream<_i10.UserSettings>);

  @override
  _i3.Future<void> updateSettings(_i10.UserSettings? settings) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [settings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
