name: functions
description: Firebase Cloud Functions for Nothing Ever Happens compiled to JavaScript.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.11.0
  js: ^0.7.1

dev_dependencies:
  test: ^1.24.0
  mocktail: ^1.0.4
